apiVersion: apps/v1
kind: Deployment
metadata:
  name: rm-capstone-projects
  labels:
    app: rm-capstone-projects
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rm-capstone-projects
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rm-capstone-projects
    spec:
      containers:
      - name: rm-capstone-projects
        imagePullPolicy: Always
        image: ashish223281/rm-capstone
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rm-capstone-project
  labels:
    app: rm-capstone-project
spec:
  type: LoadBalancer
  selector:
    app: rm-capstone-project
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
